# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kyungbin Kim
title: MS Student
email: binbin10@korea.ac.kr
# website: www.github.com/binbin-1010

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  binbin-1010
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: binbin_.k
linkedin_username: kyungbin-kim-35023824a
# xing_username: jekyll
# pinterest_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-university
  url: comsys-lab.github.io
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Kyungbin (binbin), and I am a Master's student in Electrical & Electronic Engineering at Korea University.  
  My research focuses on **next-generation memory systems**, particularly in **Compute Express Link (CXL) and tiered memory management** for AI and high-performance computing (HPC).  

  I have experience in **low-level system programming**, memory optimization, and performance tuning for large-scale computing environments.  
  My work involves **analyzing memory access patterns, developing efficient memory management techniques, and optimizing system performance for AI workloads**.  

  I am most skilled in: <mark>Memory Systems</mark>, <mark>Operating Systems</mark>, and <mark>Low-Level System Programming</mark>.


content:
  - title: Research # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Memory Systems
        # link: github.com/sproogen
        # # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Researching next-generation memory systems to enhance performance and scalability in AI and high-performance computing.
        description: | # this will include new lines to allow paragraphs
          My research focuses on **innovative memory architectures** to support the increasing demands of modern computing.  
          I explore **Compute Express Link (CXL) and tiered memory systems** to optimize memory efficiency, reduce latency, and improve scalability.

          - Investigating **CXL-based memory disaggregation** to enhance resource utilization in datacenters.  
          - Optimizing **tiered memory management** for AI workloads and high-performance computing (HPC).  
          - Exploring **hotness-aware memory techniques** to improve data locality and reduce access overhead.  
          - Developing advanced memory architectures to support the growing complexity of computing infrastructure.

          This research aims to push the boundaries of **next-generation memory systems**, ensuring efficient and scalable memory solutions for AI, cloud computing, and HPC.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: LG Display
        link: https://www.lgdisplay.com/eng
        # link_text: boringcompany.com
        sub_title: Process Development Engineer
        caption: January 2022 - March 2025
        quote: >
          Optimized microLED transfer processes through data-driven analysis and defect reduction strategies.
        description: | # this will include new lines to allow paragraphs
          Led the development and optimization of microLED transfer processes in collaboration with Apple, ensuring high-yield and scalable manufacturing. 

          - **Collaborated with Apple** to refine MTT (MicroLED Transfer Technology) specifications and improve AOI accuracy.
          - **Automated wafer defect analysis** using macros & VBA, enhancing defect detection efficiency.
          - **Developed XML conversion tools** for defect data processing, streamlining quality control workflows.
          - **Analyzed OEE (Overall Equipment Effectiveness)** to optimize production capacity and required equipment.
          - **Designed and conducted reliability tests**, including **Fiducial Quality verification, Nano Bump analysis, and Clamp Time Sweep**.
          - **Implemented Adaptive Maintenance** strategies to enhance production stability.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Korea University
        caption: Setpember 2024 - Present 
        sub_title: MS in Electric & Electronic Engineering
        description: | # this will include new lines to allow paragraphs
        description: | # this will include new lines to allow paragraphs
          Currently advancing my knowledge in **system software and high-performance computing**,  
          focusing on **machine learning performance optimization and memory management**.  
          Exploring **low-level system programming and hardware acceleration**, utilizing **C, C++, and Python**.  
          Gaining experience in **Compute Express Link (CXL) technology** and **server-side ML deployment**.

      - layout: left
        title: Dongguk University
        caption: 2016 - 2022
        sub_title: BS in Electronic & Electrical Engineering
        description: | # this will include new lines to allow paragraphs
          Studied **object-oriented programming (C++)** and **computer algorithms**, developing strong analytical and problem-solving skills.  
          Completed **external training in digital system design**, gaining experience with **hardware description languages (HDL) and FPGA programming**.  
          Led a **senior capstone project**, designing a **smart advertisement cart** using **E-paper, ESP32, and Bluetooth communication** for real-time ad updates.  
          Designed and prototyped **custom PCB circuits**, optimizing **power management** and **signal integrity** in embedded systems.

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
